anim: anim.c membrane.c pend.c overrelax.c
	gcc anim.c -lGL -lGLU -lglut -lm -o anim 
	gcc animsmooth.c -lGL -lGLU -lglut -lm -o animsmooth 
	gcc membrane.c -lm -o membrane
	gcc pend.c -lm -o pend
	gcc overrelax.c -lm -o overrelax
	gcc balls_box_masses.c -lm -o balls_box
